baseURL = "https://sysengineering.ir"
languageCode = "fa"
enableEmoji= true
title = "جامعه طراحان سیستم"
theme = "bare"
enableRobotsTXT = true

[taxonomies]
  tag = "tags"
  series = "series"

[params]
mainSections = ["posts"]
author = "جامعه طراحان سیستم"
repoLink = "https://github.com/Sys-Engineering"
description = 'نشر تجربیات و دانش؛ اینجا کلمات بر تراشه‌ها سوار هستند.'
disableAttribution = true
postcss = false
includeAuthorInTitle = true

[[params.social]]
icon = "github"
url = "https://github.com/Sys-Engineering"
