name: github pages

on:
  push:
    branches:
      - master
      - development

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'          

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.68.3"

      - name: Build Theme
        run:  | 
                cd ./themes/vivid
                npm i -g yarn 
                npm i -g gulp
                yarn
                gulp

      - name: Build Hugo
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: sys-engineering/sys-engineering.github.io
          publish_branch: master
          publish_dir: ./public
          cname: sysengineering.ir
          full_commit_message: ${{ github.event.head_commit.message }}
